services:
  # ===============================
  # GPU MODE
  # ===============================
  libretranslate:
    build:
      context: .
      dockerfile: Dockerfile.gpu
    profiles: ["gpu"]
    container_name: libretranslate
    gpus: all

    ports:
      - "5000:5000"

    environment:
      LT_LOAD_ONLY: "en,vi"
      LT_THREADS: "1"
      LT_DISABLE_WEB_UI: "true"
      LT_DISABLE_FILES_TRANSLATION: "true"

      CT2_FORCE_CUDA: "1"
      CT2_CUDA_ALLOW_FP16: "1"
      CUDA_VISIBLE_DEVICES: "0"
      CT2_CUDA_MEMORY_FRACTION: "0.7"

    volumes:
      - lt-models:/root/.local

    restart: unless-stopped


  # ===============================
  # CPU MODE (override same service name)
  # ===============================
  libretranslate-cpu:
    image: libretranslate/libretranslate
    profiles: ["cpu"]
    container_name: libretranslate

    ports:
      - "5000:5000"

    environment:
      LT_LOAD_ONLY: "en,vi"
      LT_THREADS: "2"
      LT_DISABLE_WEB_UI: "true"
      LT_DISABLE_FILES_TRANSLATION: "true"

    volumes:
      - lt-models:/home/libretranslate/.local

    restart: unless-stopped

volumes:
  lt-models: